[build]
publish = "dist"
command = "yarn build"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/parking2"
  to = "https://www.globalairportparking.com/fll/1767654/best-western-plus-fort-lauderdale-fll-airport-cruise-port-parking-special-deal"
  status = 301
  force = true


  [[redirects]]
  from = "/parking3"
  to = "  https://www.globalairportparking.com/blog/on-airport-off-airport-parking-cost-comparison/"
  status = 301
  force = true


