backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false, hint: "Used for SEO meta description." }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Authors", name: "authors", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { name: "noindex", label: "No Index", widget: "boolean", default: false }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false, hint: "Used for SEO meta description." }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { name: "noindex", label: "No Index", widget: "boolean", default: false }

  - name: "content-planner"
    label: "Content Planner"
    files:
      - name: "planner"
        label: "Content Notes"
        file: "content/planner/planner.json"
        format: "json"
        editor:
          preview: false
        fields:
          - { name: "notes", label: "Notes", widget: "text", hint: "Use this as your planning scratchpad." }
